# -*- coding: utf-8 -*-
"""task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oDGymftabmmISEYglK7SpB4oMIvXX2fT
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install jira;
# from jira import JIRA
# from IPython.display import HTML
# import getpass
# import json
# import pandas as pd

jira=JIRA("http://phaniraj123.atlassian.net",basic_auth=("vempati.phaniraj123@gmail.com","ATATT3xFfGF0eS8BlU_3TiGP7rwfIVFFKz_Q0HQ4Pr7Wfo5Y0vniPoPTCw1_8ouot8ruJIYUP5V4ysUyiX99hENeuBiFI-cjjfyvFEt7ybZ0w6dbVC610DpQp2Ev7RwIIqPsdF2crqswWecdi0rBU2-n2OtGyGVJSdCFjjxoysxgRvdZWo9zjtM=38C705D1"))

project="test"
issue=jira.search_issues("project="+project)

for i in issue:
  print(i.key)