# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFKYgGWWQHttqTNjxqDXMA3H8KiaiW7r
"""

import requests
from requests.auth import HTTPBasicAuth
import json
url = "https://phaniraj123.atlassian.net/rest/api/3/myself"
auth = HTTPBasicAuth("vempati.phaniraj123@gmail.com", "ATATT3xFfGF0WP1UCV_KyoiaCy1bXXtPwplDVI5hhhYVbXHohYD0xWo_i-j536oUIEB99AgPs_8TH5ZmVdCRNZPmMJLKWqD5NCOqlAxmpNxNYXPCXRhs_3NUxwf1m8Obi2ipIbfeuFe-zTygS9vUAJAC5pxqwu0rAdDHBviPRfXyoTLhMFPtOFo=1EEB2009")

headers = {
  "Accept": "application/json"
}
response = requests.request(
   "GET",
   url,
   headers=headers,
   auth=auth
)
print(json.dumps(json.loads(response.text), sort_keys=True, indent=4, separators=(",", ": ")))



import requests
from requests.auth import HTTPBasicAuth
import json
url = "https://phaniraj123.atlassian.net/rest/api/3/project"
auth = HTTPBasicAuth("vempati.phaniraj123@gmail.com", "ATATT3xFfGF0WP1UCV_KyoiaCy1bXXtPwplDVI5hhhYVbXHohYD0xWo_i-j536oUIEB99AgPs_8TH5ZmVdCRNZPmMJLKWqD5NCOqlAxmpNxNYXPCXRhs_3NUxwf1m8Obi2ipIbfeuFe-zTygS9vUAJAC5pxqwu0rAdDHBviPRfXyoTLhMFPtOFo=1EEB2009")

headers = {
  "Accept": "application/json"
}
response = requests.request(
   "GET",
   url,
   headers=headers,
   auth=auth
)
print(json.dumps(json.loads(response.text), sort_keys=True, indent=4, separators=(",", ": ")))